# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/suma_de_manos',
                'doc_host': 'https://mochacchin.github.io',
                'git_url': 'https://github.com/mochacchin/suma_de_manos',
                'lib_path': 'suma_de_manos'},
  'syms': {'suma_de_manos.core': {'suma_de_manos.core.foo': ('core.html#foo', 'suma_de_manos/core.py')}}}
